# Generated by Django 5.1.5 on 2025-01-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adddesign',
            name='discription',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
