# Generated by Django 5.1.5 on 2025-01-23 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_alter_adddesign_discription'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='adddesign',
            new_name='add_design',
        ),
    ]
