# Generated by Django 5.1.5 on 2025-01-23 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0003_rename_adddesign_add_design'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_design',
            name='discription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='add_design',
            name='price',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
