# Generated by Django 5.1.5 on 2025-01-23 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0004_alter_add_design_discription_alter_add_design_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='add_design',
            new_name='AddDesign',
        ),
    ]
