# Generated by Django 5.1.5 on 2025-01-24 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0005_rename_add_design_adddesign'),
        ('Guest', '0003_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='adddesign',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Guest.customer'),
            preserve_default=False,
        ),
    ]
