# Generated by Django 5.1.5 on 2025-01-26 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0006_adddesign_user'),
        ('Guest', '0003_customer'),
        ('Shop', '0002_dress_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.dress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.customer')),
            ],
        ),
    ]
