# Generated by Django 5.1.5 on 2025-01-26 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0008_adddesign_status'),
        ('Guest', '0003_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.adddesign')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.shop')),
            ],
        ),
    ]
