# Generated by Django 5.1.5 on 2025-01-26 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_customer'),
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dress',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Guest.shop'),
            preserve_default=False,
        ),
    ]
