# Generated by Django 5.1.5 on 2025-01-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0002_shop_logo_shop_district_shop_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('place', models.CharField(max_length=100)),
                ('district', models.CharField(choices=[('ernakulam', 'Ernakulam'), ('kollam', 'Kollam'), ('idukki', 'Idukki')], max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='Customer_image/')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
